# -*- coding: utf-8 -*-
"""1_Limpieza_exploracion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DQdY4AiRLrnMM6pn-t-KwBt3m9BFY6wr

#1 Comprension y Limpieza de los datos
"""

#### Cargar paquetes siempre al inicio

import pandas as pd

